In [1]:
from sqlalchemy import create_engine
import pandas as pd

Load dataset

In [2]:
df = pd.read_csv("ev_charging_data.csv", parse_dates=["datetime"])

In [2]:
engine = create_engine(
    "postgresql+psycopg2://postgres:Nikeade1@localhost:5432/ev_pricing"
)

# Test connection
with engine.connect() as conn:
    print("Connected successfully!")

Connected successfully!

In [ ]:
df.to_sql(
    "charging_sessions",
    engine,
    if_exists="append",
    index=False
)

Load static_pricing data

In [4]:
static_df = pd.read_csv("static_pricing_data.csv")

In [6]:
static_df

,session_id,static_markup_percent,static_retail_price,static_revenue,static_cost,static_profit
0,1,0.25,0.1876,20.045131,20.121945,-0.076814
1,2,0.25,0.1876,11.952963,11.611514,0.341449
2,3,0.25,0.1876,4.635186,5.110260,-0.475075
3,4,0.25,0.1876,9.395048,9.945060,-0.550012
4,5,0.25,0.1876,9.024892,10.010820,-0.985928
...,...,...,...,...,...,...
2875,2876,0.25,0.1876,26.546507,14.440953,12.105554
2876,2877,0.25,0.1876,39.146682,26.881770,12.264912
2877,2878,0.25,0.1876,22.638709,17.860739,4.777969
2878,2879,0.25,0.1876,14.771680,12.126304,2.645376
2879,2880,0.25,0.1876,3.088398,3.161638,-0.073240

In [7]:
static_df.to_sql(
    "static_pricing",
    engine,
    if_exists="replace",
    index=False
)

880

loading dynamic pricing data

In [5]:
dynamic_pricing_df = pd.read_csv("dynamic_pricing.csv")

In [6]:
dynamic_pricing_df.head()

,session_id,dynamic_price,predicted_energy_sold_kwh,Adjusted_demand_kwh,dynamic_revenue,dynamic_profit
0,1,0.274725,106.850447,87.001109,23.901360,7.517417
1,2,0.250495,63.715196,55.170729,13.819972,3.765609
2,3,0.271461,24.707828,20.289849,5.507907,1.311406
3,4,0.267665,50.080246,41.530845,11.116342,2.869043
4,5,0.279683,48.107129,38.661801,10.813049,2.767749

In [7]:
dynamic_pricing_df.to_sql(
    "dynamic_pricing",
    engine,
    if_exists="replace",
    index=False
)

880