In [1]:
import pandas as pd

Loading the data frame we have after linear model

In [8]:
df = pd.read_csv('model.csv')

In [9]:
df.head()

,session_id,datetime,hour,day_of_week,is_weekend,temperature,wholesale_price,retail_price,charging_sessions,energy_per_session,energy_sold_kwh,predicted_energy_sold_kwh
0,1,2025-01-01 00:00:00,0,2,0,25.127134,0.188319,0.235398,5,13.923257,69.616286,106.850447
1,2,2025-01-01 01:00:00,1,2,0,25.190453,0.182241,0.227801,3,25.697249,77.091747,63.715196
2,3,2025-01-01 02:00:00,2,2,0,27.573437,0.206828,0.258534,1,25.714565,25.714565,24.707828
3,4,2025-01-01 03:00:00,3,2,0,28.977748,0.198582,0.248228,2,20.320314,40.640627,50.080246
4,5,2025-01-01 04:00:00,4,2,0,28.294179,0.208094,0.260118,2,24.234807,48.469613,48.107129

In [10]:
static_df = pd.DataFrame()
static_df["session_id"] = df['session_id']
static_df['static_markup_percent'] = 0.25 #25%
static_df["static_retail_price"] = df["wholesale_price"].mean() * 1.25  # using a 25% markup 
static_df["static_revenue"] = static_df["static_retail_price"] * df["predicted_energy_sold_kwh"]
static_df["static_cost"] = df["predicted_energy_sold_kwh"] * df["wholesale_price"]
static_df["static_profit"] = static_df["static_revenue"] - static_df["static_cost"]

In [11]:
static_df.head()

,session_id,static_markup_percent,static_retail_price,static_revenue,static_cost,static_profit
0,1,0.25,0.1876,20.045131,20.121945,-0.076814
1,2,0.25,0.1876,11.952963,11.611514,0.341449
2,3,0.25,0.1876,4.635186,5.110260,-0.475075
3,4,0.25,0.1876,9.395048,9.945060,-0.550012
4,5,0.25,0.1876,9.024892,10.010820,-0.985928

In [ ]:
static_df.to_csv('static_pricing_data.csv', index = False)

: